### PR TITLE
Update TiddlyWiki to version 5.3.3.

### PR DESCRIPTION
**Pull request by th**

### CODE REVIEW

**Comment by qbit** [comment]
Nice, ty! How did you fetch the html file?

I'd like to add checksums so people can verify themselves if `empty.html` is what it should be, but when I download from https://tiddlywiki.com/ I get a slightly different file:

```
--- /home/qbit/Downloads/empty.html     2024-05-05 07:45:09.194046820 -0600
+++ empty-5.3.3.html    2024-05-05 07:46:20.566051198 -0600
@@ -1,7 +1,7 @@
 
 <!doctype html>
 <!-- The following comment is called a MOTW comment and is necessary for the TiddlyIE Internet Explorer extension -->
-<!-- saved from url=(0021)https://tiddlywiki.com -->
+<!-- saved from url=(0021)https://tiddlywiki.com -->
 <html lang="en-GB">
 <head>
 <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
```

**Comment by th** [comment]
What's the difference, the + and - lines look identical?

I clicked on the green download button at https://tiddlywiki.com/.

I think I opened it afterwards, to check the version. Maybe that already changed something?

You should probably download it yourself, to make sure I didn't sneak anything in.

Unfortunately, the release at https://github.com/Jermolene/TiddlyWiki5/releases/tag/v5.3.3 doesn't seem to have the single file, only the npm sources.

**Comment by qbit** [comment]
> What's the difference, the + and - lines look identical?

Mine has the "saved from url" line and yours doesn't.

**Comment by qbit** [comment]
> > What's the difference, the + and - lines look identical?
> 
> Mine has the "saved from url" line and yours doesn't.

er.. Mine has a ^M and yours doesn't :P

**Comment by th** [comment]
Sorry, didn't see it in the GitHub viewer.

CRLF vs. LF... so it's Windows vs. Linux.

**Comment by qbit** [comment]
Interesting. I downloaded it from my NixOS machine. They must be doing some detection / modification stuff..

**Pull request merged**
